def get_suggestions(body_type: str):
    suggestions = {
        "pear": [
            { "item": "A-line skirts", "image": "https://images.unsplash.com/photo-1562158070-8a53b201bc1b", "gender": "female" },
            { "item": "Off-shoulder tops", "image": "https://example.com/off_shoulder_top.jpg", "gender": "female" },
            { "item": "Bootcut jeans", "image": "https://example.com/bootcut_jeans.jpg", "gender": "female" },
            { "item": "Structured jackets", "image": "https://example.com/structured_jacket.jpg", "gender": "female" },
            { "item": "Fit-and-flare dresses", "image": "https://example.com/fit_flare_dress.jpg", "gender": "female" },
            { "item": "Straight-leg pants", "image": "https://example.com/straight_leg_pants_m.jpg", "gender": "male" },
            { "item": "Dark-wash jeans", "image": "https://example.com/dark_wash_jeans_m.jpg", "gender": "male" },
            { "item": "Layered tops", "image": "https://example.com/layered_tops_m.jpg", "gender": "male" },
            { "item": "Blazers with structure", "image": "https://example.com/blazer_pear_m.jpg", "gender": "male" },
        ],
        "rectangle": [
            { "item": "Wrap dresses", "image": "https://example.com/wrap_dress.jpg", "gender": "female" },
            { "item": "Peplum tops", "image": "https://example.com/peplum_top.jpg", "gender": "female" },
            { "item": "Ruffled blouses", "image": "https://example.com/ruffled_blouse.jpg", "gender": "female" },
            { "item": "Layered outfits", "image": "https://example.com/layered_outfit.jpg", "gender": "female" },
            { "item": "Belts to define waist", "image": "https://example.com/belted_waist.jpg", "gender": "female" },
            { "item": "Slim-fit blazers", "image": "https://example.com/slim_fit_blazer_m.jpg", "gender": "male" },
            { "item": "Henley shirts", "image": "https://example.com/henley_m.jpg", "gender": "male" },
            { "item": "Bomber jackets", "image": "https://example.com/bomber_jacket_m.jpg", "gender": "male" },
            { "item": "Cuffed chinos", "image": "https://example.com/cuffed_chinos_m.jpg", "gender": "male" },
        ],
        "hourglass": [
            { "item": "Fitted dresses", "image": "https://example.com/fitted_dress.jpg", "gender": "female" },
            { "item": "High-waisted pants", "image": "https://example.com/high_waist_pants.jpg", "gender": "female" },
            { "item": "Wrap tops", "image": "https://example.com/wrap_top.jpg", "gender": "female" },
            { "item": "Bodycon dresses", "image": "https://example.com/bodycon_dress.jpg", "gender": "female" },
            { "item": "Tailored blazers", "image": "https://example.com/tailored_blazer.jpg", "gender": "female" },
            { "item": "Athletic-fit shirts", "image": "https://example.com/athletic_shirt_m.jpg", "gender": "male" },
            { "item": "Tapered trousers", "image": "https://example.com/tapered_trousers_m.jpg", "gender": "male" },
            { "item": "Fitted polos", "image": "https://example.com/fitted_polo_m.jpg", "gender": "male" },
            { "item": "Layered jackets", "image": "https://example.com/layered_jacket_m.jpg", "gender": "male" },
        ],
        "apple": [
            { "item": "Empire waist tops", "image": "https://example.com/empire_waist_top.jpg", "gender": "female" },
            { "item": "Flowy tunics", "image": "https://example.com/flowy_tunic.jpg", "gender": "female" },
            { "item": "V-neck blouses", "image": "https://example.com/v_neck_blouse.jpg", "gender": "female" },
            { "item": "Straight-leg jeans", "image": "https://example.com/straight_leg_jeans.jpg", "gender": "female" },
            { "item": "Long cardigans", "image": "https://example.com/long_cardigan.jpg", "gender": "female" },
            { "item": "Vertical striped shirts", "image": "https://example.com/vertical_stripes_m.jpg", "gender": "male" },
            { "item": "Dark monochrome tops", "image": "https://example.com/dark_top_m.jpg", "gender": "male" },
            { "item": "Unstructured blazers", "image": "https://example.com/unstructured_blazer_m.jpg", "gender": "male" },
            { "item": "V-neck sweaters", "image": "https://example.com/vneck_sweater_m.jpg", "gender": "male" },
        ],
        "inverted_triangle": [
            { "item": "V-neck tops", "image": "https://example.com/v_neck_top.jpg", "gender": "female" },
            { "item": "Wide-leg pants", "image": "https://example.com/wide_leg_pants.jpg", "gender": "female" },
            { "item": "A-line skirts", "image": "https://example.com/a_line_skirt2.jpg", "gender": "female" },
            { "item": "Flowy blouses", "image": "https://example.com/flowy_blouse.jpg", "gender": "female" },
            { "item": "Dropped shoulder tops", "image": "https://example.com/dropped_shoulder.jpg", "gender": "female" },
            { "item": "Relaxed-fit trousers", "image": "https://example.com/relaxed_fit_trousers_m.jpg", "gender": "male" },
            { "item": "Printed or color-blocked bottoms", "image": "https://example.com/printed_pants_m.jpg", "gender": "male" },
            { "item": "Crew neck t-shirts", "image": "https://example.com/crew_neck_m.jpg", "gender": "male" },
            { "item": "Hoodies or pullovers", "image": "https://example.com/pullover_m.jpg", "gender": "male" },
        ],
    }

    return suggestions.get(body_type.lower(), [])
